baseURL = 'https://fourcels.github.io/'
languageCode = 'en-us'
title = "Kiyan's Blog"
theme = "github.com/Mitrichius/hugo-theme-anubis"

[params]
style = "dark-without-switcher"
giscus = true

[[params.social]]
id = "github"
name = "fourcels"
